name: urban_glide_driver_selfie
description: Driver selfie upload + local device biometric auth (privacy-preserving)
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  firebase_database: ^10.2.0
  firebase_storage: ^11.0.0
  image_picker: ^0.8.7+4
  local_auth: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
